// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads/AdIdentity.tsx": () => import("../components/mockups/ads/AdIdentity.tsx"),
  "./components/mockups/ads/AdOutcome.tsx": () => import("../components/mockups/ads/AdOutcome.tsx"),
  "./components/mockups/ads/AdPain.tsx": () => import("../components/mockups/ads/AdPain.tsx")
};
